// "use client"
import type { Metadata } from "next";

import "./globals.css";
import SessionWrapper from "@/components/SessionWraper";
import { CssBaseline } from "@mui/material";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <SessionWrapper>
      <CssBaseline/>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SessionWrapper>
  );
}