import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { CssBaseline } from "@mui/material";
import Header from "@/components/header/header";
import Layout from "@/components/Layout/layout";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionWrapper>
        <html lang="en">
          <body>
            <CssBaseline/>
            <Header/>
            <Layout>
              {children}
            </Layout></body>
        </html>
		</SessionWrapper>
	);
}
